# Site settings
title: Aryeh Leon Radle-Dessiatink
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

baseurl: ""
url: https://arieradle.github.io

title: "Aryeh Radle, Chief Architect"
# User settings
username: Aryéh Radlé
user_description: With over two decades of rich expertise in Cloud, Solutions, Enterprise, and Software Architecture and development, I serve as a seasoned Chief Architect and Head of Cloud. My focus lies in spearheading transformative initiatives encompassing both enterprise and government cloud migration. Evaluating RFP responses, crafting robust business strategies, and navigating multifaceted stakeholder environments are among my specialized skills honed over the years. Recognized for not only technical proficiency but also adept leadership, I thrive in steering complex projects towards successful outcomes within multinational landscapes.
user_title: Chief Architect
email: arie.radle@gmail.com
linkedin_username: arieleonradle

exclude: ['package.json', 'src', 'node_modules', 'vendor']
